brew "deno"
brew "fzf"
brew "ghq"
brew "jq"
# brew "helm"
# brew "kubectl", link: true
# brew "kube-ps1"
# brew "kustomize"
brew "maven"
brew "nodenv"
brew "openjdk"
brew "poppler"
brew "pyenv"
brew "tmux"
# vimspector crashed on latest vim
# So I installed vim 8.2 by apt from ppa:jonathonf/vim
# brew "vim"
brew "wget"
